# Generated by Django 3.2.7 on 2021-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('available', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('status', models.CharField(choices=[('m', 'موجود'), ('n', 'ناموجود')], max_length=1)),
            ],
        ),
    ]
